version: '3'

services:
    app:
        container_name: unso
        build: 
            context: ../
            dockerfile: docker/Dockerfile
        volumes:
            - ../.:/code
        ports:
            - 8000:8000
        env_file:
            - ../.env
        depends_on:
            - db
        restart: always

    db:
        image: postgres:12-alpine
        container_name: unsodb
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            # env variables will be manually created using a .env file in
            # root directory folder
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_HOST=${POSTGRES_DB_HOST}
            - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
            # we will be using scram for passwords
            # assuming we only have a few trusted users (can setup LDAP for large # of users)
            # you can download the whitepaper here for additional ref:
            # https://www.enterprisedb.com/promote/security-best-practices-postgresql
            - POSTGRES_INITDB_ARGS="--auth-host=scram-sha-256"
        ports:
            - "5432:5432"

    nginx:
        container_name: unso_nginx
        image: nginx:1.14
        restart: always
        build:
            context: ../nginx
            dockerfile: Dockerfile_nginx
        ports:
            - 443:443
            - 80:80
        depends_on:
            - app

volumes:
    postgres_data:
        external: true